INSERT INTO City(CityName, Population, StateCode) VALUES('Akron',7684915, 'MO');
INSERT INTO City(CityName, Population, StateCode) VALUES('Akron',5947796, 'OH');
INSERT INTO City(CityName, Population, StateCode) VALUES('Akron',3878285, 'RI');
INSERT INTO City(CityName, Population, StateCode) VALUES('Albuquerque',3608365, 'NV');
INSERT INTO City(CityName, Population, StateCode) VALUES('Albuquerque',6610173, 'OR');
INSERT INTO City(CityName, Population, StateCode) VALUES('Albuquerque',4126810, 'WV');
INSERT INTO City(CityName, Population, StateCode) VALUES('Anaheim',6607294, 'CA');
INSERT INTO City(CityName, Population, StateCode) VALUES('Anaheim',2075107, 'HI');
INSERT INTO City(CityName, Population, StateCode) VALUES('Anaheim',5697569, 'KS');
INSERT INTO City(CityName, Population, StateCode) VALUES('Anchorage',6784867, 'FL');
INSERT INTO City(CityName, Population, StateCode) VALUES('Anchorage',5670054, 'MO');
INSERT INTO City(CityName, Population, StateCode) VALUES('Anchorage',1817211, 'MT');
INSERT INTO City(CityName, Population, StateCode) VALUES('Arlington',186497, 'CA');
INSERT INTO City(CityName, Population, StateCode) VALUES('Arlington',8824634, 'KS');
INSERT INTO City(CityName, Population, StateCode) VALUES('Arlington',4590795, 'WA');
INSERT INTO City(CityName, Population, StateCode) VALUES('Atlanta',362177, 'AR');
INSERT INTO City(CityName, Population, StateCode) VALUES('Atlanta',9791703, 'MN');
INSERT INTO City(CityName, Population, StateCode) VALUES('Atlanta',5727249, 'TX');
INSERT INTO City(CityName, Population, StateCode) VALUES('Aurora',6387356, 'NY');
INSERT INTO City(CityName, Population, StateCode) VALUES('Aurora',6606856, 'WA');
INSERT INTO City(CityName, Population, StateCode) VALUES('Austin',11892016, 'AR');
INSERT INTO City(CityName, Population, StateCode) VALUES('Austin',2853640, 'TX');
INSERT INTO City(CityName, Population, StateCode) VALUES('Austin',8950617, 'VT');
INSERT INTO City(CityName, Population, StateCode) VALUES('Bakersfield',2040079, 'CA');
INSERT INTO City(CityName, Population, StateCode) VALUES('Bakersfield',7086815, 'KS');
INSERT INTO City(CityName, Population, StateCode) VALUES('Baltimore',3909086, 'NC');
INSERT INTO City(CityName, Population, StateCode) VALUES('Baltimore',4944371, 'VT');
INSERT INTO City(CityName, Population, StateCode) VALUES('Baltimore',3411447, 'WY');
INSERT INTO City(CityName, Population, StateCode) VALUES('Baton Rouge',8041780, 'AZ');
INSERT INTO City(CityName, Population, StateCode) VALUES('Baton Rouge',982389, 'DE');
INSERT INTO City(CityName, Population, StateCode) VALUES('Baton Rouge',1189996, 'GA');
INSERT INTO City(CityName, Population, StateCode) VALUES('Birmingham',6323271, 'TX');
INSERT INTO City(CityName, Population, StateCode) VALUES('Birmingham',7239195, 'VT');
INSERT INTO City(CityName, Population, StateCode) VALUES('Birmingham',6407747, 'WY');
INSERT INTO City(CityName, Population, StateCode) VALUES('Boston',11235916, 'CO');
INSERT INTO City(CityName, Population, StateCode) VALUES('Boston',9761036, 'NV');
INSERT INTO City(CityName, Population, StateCode) VALUES('Boston',2211765, 'WV');
INSERT INTO City(CityName, Population, StateCode) VALUES('Buffalo',6568145, 'AL');
INSERT INTO City(CityName, Population, StateCode) VALUES('Buffalo',9513968, 'IA');
INSERT INTO City(CityName, Population, StateCode) VALUES('Charlotte',1055095, 'CA');
INSERT INTO City(CityName, Population, StateCode) VALUES('Charlotte',7082890, 'NY');
INSERT INTO City(CityName, Population, StateCode) VALUES('Charlotte',11640843, 'WA');
INSERT INTO City(CityName, Population, StateCode) VALUES('Chicago',2519487, 'MI');
INSERT INTO City(CityName, Population, StateCode) VALUES('Chicago',7223750, 'NH');
INSERT INTO City(CityName, Population, StateCode) VALUES('Cincinnati',5894247, 'CO');
INSERT INTO City(CityName, Population, StateCode) VALUES('Cincinnati',474864, 'MA');
INSERT INTO City(CityName, Population, StateCode) VALUES('Cincinnati',5880905, 'WV');
INSERT INTO City(CityName, Population, StateCode) VALUES('Cleveland',5507665, 'CT');
INSERT INTO City(CityName, Population, StateCode) VALUES('Cleveland',9953124, 'IL');
INSERT INTO City(CityName, Population, StateCode) VALUES('Cleveland',10747084, 'OK');
INSERT INTO City(CityName, Population, StateCode) VALUES('Colorado',2409313, 'AZ');
INSERT INTO City(CityName, Population, StateCode) VALUES('Colorado',4478196, 'DE');
INSERT INTO City(CityName, Population, StateCode) VALUES('Colorado',8013845, 'MD');
INSERT INTO City(CityName, Population, StateCode) VALUES('Columbus',2217539, 'ID');
INSERT INTO City(CityName, Population, StateCode) VALUES('Columbus',970026, 'IL');
INSERT INTO City(CityName, Population, StateCode) VALUES('Corpus Christi',7798000, 'IN');
INSERT INTO City(CityName, Population, StateCode) VALUES('Corpus Christi',11913487, 'LA');
INSERT INTO City(CityName, Population, StateCode) VALUES('Corpus Christi',7966699, 'NE');
INSERT INTO City(CityName, Population, StateCode) VALUES('Dallas',8905844, 'CT');
INSERT INTO City(CityName, Population, StateCode) VALUES('Dallas',8015731, 'OK');
INSERT INTO City(CityName, Population, StateCode) VALUES('Dallas',1267701, 'WI');
INSERT INTO City(CityName, Population, StateCode) VALUES('Dayton',5242806, 'IL');
INSERT INTO City(CityName, Population, StateCode) VALUES('Dayton',7083222, 'OK');
INSERT INTO City(CityName, Population, StateCode) VALUES('Denver',8746205, 'NV');
INSERT INTO City(CityName, Population, StateCode) VALUES('Denver',11761169, 'WV');
INSERT INTO City(CityName, Population, StateCode) VALUES('Des Moines',11838579, 'NC');
INSERT INTO City(CityName, Population, StateCode) VALUES('Des Moines',221583, 'OH');
INSERT INTO City(CityName, Population, StateCode) VALUES('Des Moines',1615094, 'RI');
INSERT INTO City(CityName, Population, StateCode) VALUES('Detroit',6452123, 'KY');
INSERT INTO City(CityName, Population, StateCode) VALUES('Detroit',9377710, 'MN');
INSERT INTO City(CityName, Population, StateCode) VALUES('Detroit',5859113, 'VA');
INSERT INTO City(CityName, Population, StateCode) VALUES('El Paso',9857482, 'FL');
INSERT INTO City(CityName, Population, StateCode) VALUES('El Paso',8384616, 'MO');
INSERT INTO City(CityName, Population, StateCode) VALUES('El Paso',1609323, 'OH');
INSERT INTO City(CityName, Population, StateCode) VALUES('Fort Wayne',6711652, 'AZ');
INSERT INTO City(CityName, Population, StateCode) VALUES('Fort Wayne',5063405, 'DE');
INSERT INTO City(CityName, Population, StateCode) VALUES('Fort Worth',8277959, 'CO');
INSERT INTO City(CityName, Population, StateCode) VALUES('Fort Worth',2926957, 'MA');
INSERT INTO City(CityName, Population, StateCode) VALUES('Fort Worth',1067737, 'UT');
INSERT INTO City(CityName, Population, StateCode) VALUES('Fremont',4567408, 'ID');
INSERT INTO City(CityName, Population, StateCode) VALUES('Fremont',10148986, 'PA');
INSERT INTO City(CityName, Population, StateCode) VALUES('Fresno',8117, 'MA');
INSERT INTO City(CityName, Population, StateCode) VALUES('Fresno',10820299, 'UT');
INSERT INTO City(CityName, Population, StateCode) VALUES('Garland',526447, 'IA');
INSERT INTO City(CityName, Population, StateCode) VALUES('Garland',3528912, 'SD');
INSERT INTO City(CityName, Population, StateCode) VALUES('Glendale',6682429, 'CT');
INSERT INTO City(CityName, Population, StateCode) VALUES('Glendale',6186100, 'WI');
INSERT INTO City(CityName, Population, StateCode) VALUES('Grand Rapids',1293704, 'FL');
INSERT INTO City(CityName, Population, StateCode) VALUES('Grand Rapids',8303138, 'MO');
INSERT INTO City(CityName, Population, StateCode) VALUES('Grand Rapids',5388088, 'OH');
INSERT INTO City(CityName, Population, StateCode) VALUES('Greensboro',7616852, 'MO');
INSERT INTO City(CityName, Population, StateCode) VALUES('Greensboro',106999, 'OH');
INSERT INTO City(CityName, Population, StateCode) VALUES('Greensboro',8379650, 'RI');
INSERT INTO City(CityName, Population, StateCode) VALUES('Hialeah',6777174, 'HI');
INSERT INTO City(CityName, Population, StateCode) VALUES('Hialeah',9384901, 'KS');
INSERT INTO City(CityName, Population, StateCode) VALUES('Hialeah',6903443, 'NM');
INSERT INTO City(CityName, Population, StateCode) VALUES('Honolulu',11804872, 'GA');
INSERT INTO City(CityName, Population, StateCode) VALUES('Honolulu',3451405, 'WI');
INSERT INTO City(CityName, Population, StateCode) VALUES('Houston',1247696, 'NJ');
INSERT INTO City(CityName, Population, StateCode) VALUES('Houston',1117744, 'OR');
INSERT INTO City(CityName, Population, StateCode) VALUES('Indianapolis',5746277, 'IN');
INSERT INTO City(CityName, Population, StateCode) VALUES('Indianapolis',3631974, 'MS');
INSERT INTO City(CityName, Population, StateCode) VALUES('Indianapolis',11698053, 'NE');
INSERT INTO City(CityName, Population, StateCode) VALUES('Jackson',11301894, 'AZ');
INSERT INTO City(CityName, Population, StateCode) VALUES('Jackson',9028542, 'MD');
INSERT INTO City(CityName, Population, StateCode) VALUES('Jacksonville',10133769, 'MI');
INSERT INTO City(CityName, Population, StateCode) VALUES('Jacksonville',11372286, 'NH');
INSERT INTO City(CityName, Population, StateCode) VALUES('Jacksonville',6911804, 'TN');
INSERT INTO City(CityName, Population, StateCode) VALUES('Jersey',2058323, 'NC');
INSERT INTO City(CityName, Population, StateCode) VALUES('Jersey',3635902, 'VT');
INSERT INTO City(CityName, Population, StateCode) VALUES('Jersey',8629505, 'WY');
INSERT INTO City(CityName, Population, StateCode) VALUES('Kansas',10349326, 'ME');
INSERT INTO City(CityName, Population, StateCode) VALUES('Kansas',9927560, 'MI');
INSERT INTO City(CityName, Population, StateCode) VALUES('Kansas',11239032, 'NH');
INSERT INTO City(CityName, Population, StateCode) VALUES('Las Vegas',10190906, 'AL');
INSERT INTO City(CityName, Population, StateCode) VALUES('Las Vegas',4037431, 'ME');
INSERT INTO City(CityName, Population, StateCode) VALUES('Las Vegas',4891719, 'NH');
INSERT INTO City(CityName, Population, StateCode) VALUES('Lincoln',5878938, 'AR');
INSERT INTO City(CityName, Population, StateCode) VALUES('Lincoln',10497740, 'MN');
INSERT INTO City(CityName, Population, StateCode) VALUES('Lincoln',9334504, 'TX');
INSERT INTO City(CityName, Population, StateCode) VALUES('Little Rock',11344715, 'AR');
INSERT INTO City(CityName, Population, StateCode) VALUES('Little Rock',2785238, 'MN');
INSERT INTO City(CityName, Population, StateCode) VALUES('Little Rock',9000407, 'VA');
INSERT INTO City(CityName, Population, StateCode) VALUES('Long Beach',8263969, 'MI');
INSERT INTO City(CityName, Population, StateCode) VALUES('Long Beach',7359630, 'TN');
INSERT INTO City(CityName, Population, StateCode) VALUES('Los Angeles',9458934, 'HI');
INSERT INTO City(CityName, Population, StateCode) VALUES('Los Angeles',1020310, 'KS');
INSERT INTO City(CityName, Population, StateCode) VALUES('Louisville',9425982, 'AK');
INSERT INTO City(CityName, Population, StateCode) VALUES('Louisville',683604, 'ID');
INSERT INTO City(CityName, Population, StateCode) VALUES('Louisville',6144849, 'PA');
INSERT INTO City(CityName, Population, StateCode) VALUES('Lubbock',9938640, 'ID');
INSERT INTO City(CityName, Population, StateCode) VALUES('Lubbock',7457644, 'IL');
INSERT INTO City(CityName, Population, StateCode) VALUES('Lubbock',10361209, 'PA');
INSERT INTO City(CityName, Population, StateCode) VALUES('Madison',3809269, 'IA');
INSERT INTO City(CityName, Population, StateCode) VALUES('Madison',7693110, 'SC');
INSERT INTO City(CityName, Population, StateCode) VALUES('Madison',122326, 'SD');
INSERT INTO City(CityName, Population, StateCode) VALUES('Memphis',10955694, 'FL');
INSERT INTO City(CityName, Population, StateCode) VALUES('Memphis',6614192, 'MT');
INSERT INTO City(CityName, Population, StateCode) VALUES('Mesa',9259541, 'AK');
INSERT INTO City(CityName, Population, StateCode) VALUES('Mesa',3525057, 'ND');
INSERT INTO City(CityName, Population, StateCode) VALUES('Miami',2867463, 'MT');
INSERT INTO City(CityName, Population, StateCode) VALUES('Miami',893856, 'NY');
INSERT INTO City(CityName, Population, StateCode) VALUES('Miami',10058645, 'WA');
INSERT INTO City(CityName, Population, StateCode) VALUES('Milwaukee',8177407, 'MT');
INSERT INTO City(CityName, Population, StateCode) VALUES('Milwaukee',2446782, 'NY');
INSERT INTO City(CityName, Population, StateCode) VALUES('Minneapolis',6588284, 'NJ');
INSERT INTO City(CityName, Population, StateCode) VALUES('Minneapolis',1285783, 'NV');
INSERT INTO City(CityName, Population, StateCode) VALUES('Minneapolis',1559327, 'OR');
INSERT INTO City(CityName, Population, StateCode) VALUES('Mobile',655603, 'NC');
INSERT INTO City(CityName, Population, StateCode) VALUES('Mobile',9790261, 'OH');
INSERT INTO City(CityName, Population, StateCode) VALUES('Mobile',4854095, 'RI');
INSERT INTO City(CityName, Population, StateCode) VALUES('Montgomery',7420175, 'KY');
INSERT INTO City(CityName, Population, StateCode) VALUES('Montgomery',6239429, 'SC');
INSERT INTO City(CityName, Population, StateCode) VALUES('Montgomery',11172589, 'VA');
INSERT INTO City(CityName, Population, StateCode) VALUES('Nashville',6084440, 'IN');
INSERT INTO City(CityName, Population, StateCode) VALUES('Nashville',3985400, 'LA');
INSERT INTO City(CityName, Population, StateCode) VALUES('Nashville',9753958, 'UT');
INSERT INTO City(CityName, Population, StateCode) VALUES('New Orleans',10238768, 'IN');
INSERT INTO City(CityName, Population, StateCode) VALUES('New Orleans',6989138, 'LA');
INSERT INTO City(CityName, Population, StateCode) VALUES('New York',6259301, 'AR');
INSERT INTO City(CityName, Population, StateCode) VALUES('New York',2901954, 'TX');
INSERT INTO City(CityName, Population, StateCode) VALUES('New York',9681671, 'VT');
INSERT INTO City(CityName, Population, StateCode) VALUES('Newark',11606155, 'DE');
INSERT INTO City(CityName, Population, StateCode) VALUES('Newark',6254424, 'GA');
INSERT INTO City(CityName, Population, StateCode) VALUES('Norfolk',8985009, 'FL');
INSERT INTO City(CityName, Population, StateCode) VALUES('Norfolk',5256933, 'MT');
INSERT INTO City(CityName, Population, StateCode) VALUES('Norfolk',10795717, 'NY');
INSERT INTO City(CityName, Population, StateCode) VALUES('Oakland',7169735, 'ME');
INSERT INTO City(CityName, Population, StateCode) VALUES('Oakland',9444807, 'NH');
INSERT INTO City(CityName, Population, StateCode) VALUES('Oklahoma',9889246, 'AK');
INSERT INTO City(CityName, Population, StateCode) VALUES('Oklahoma',8640549, 'ND');
INSERT INTO City(CityName, Population, StateCode) VALUES('Oklahoma',6526590, 'NM');
INSERT INTO City(CityName, Population, StateCode) VALUES('Omaha',1994293, 'AZ');
INSERT INTO City(CityName, Population, StateCode) VALUES('Omaha',5500143, 'MD');
INSERT INTO City(CityName, Population, StateCode) VALUES('Omaha',7524170, 'MS');
INSERT INTO City(CityName, Population, StateCode) VALUES('Philadelphia',6389592, 'FL');
INSERT INTO City(CityName, Population, StateCode) VALUES('Philadelphia',3840977, 'MO');
INSERT INTO City(CityName, Population, StateCode) VALUES('Phoenix',164250, 'DE');
INSERT INTO City(CityName, Population, StateCode) VALUES('Phoenix',9021855, 'GA');
INSERT INTO City(CityName, Population, StateCode) VALUES('Phoenix',1105394, 'WI');
INSERT INTO City(CityName, Population, StateCode) VALUES('Pittsburgh',1709398, 'CO');
INSERT INTO City(CityName, Population, StateCode) VALUES('Pittsburgh',4898046, 'WV');
INSERT INTO City(CityName, Population, StateCode) VALUES('Portland',5932588, 'IN');
INSERT INTO City(CityName, Population, StateCode) VALUES('Portland',4812844, 'NE');
INSERT INTO City(CityName, Population, StateCode) VALUES('Raleigh',1703543, 'NJ');
INSERT INTO City(CityName, Population, StateCode) VALUES('Raleigh',339737, 'OR');
INSERT INTO City(CityName, Population, StateCode) VALUES('Raleigh',8307760, 'TN');
INSERT INTO City(CityName, Population, StateCode) VALUES('Richmond',6544852, 'AK');
INSERT INTO City(CityName, Population, StateCode) VALUES('Richmond',5705182, 'ND');
INSERT INTO City(CityName, Population, StateCode) VALUES('Richmond',9488065, 'PA');
INSERT INTO City(CityName, Population, StateCode) VALUES('Riverside',1681261, 'NC');
INSERT INTO City(CityName, Population, StateCode) VALUES('Riverside',8563087, 'RI');
INSERT INTO City(CityName, Population, StateCode) VALUES('Riverside',11949994, 'WY');
INSERT INTO City(CityName, Population, StateCode) VALUES('Rochester',7234299, 'NV');
INSERT INTO City(CityName, Population, StateCode) VALUES('Rochester',3486778, 'OR');
INSERT INTO City(CityName, Population, StateCode) VALUES('Sacramento',5513783, 'CA');
INSERT INTO City(CityName, Population, StateCode) VALUES('Sacramento',9567383, 'WA');
INSERT INTO City(CityName, Population, StateCode) VALUES('San Antonio',4968774, 'MD');
INSERT INTO City(CityName, Population, StateCode) VALUES('San Antonio',10495370, 'MS');
INSERT INTO City(CityName, Population, StateCode) VALUES('San Diego',194470, 'AL');
INSERT INTO City(CityName, Population, StateCode) VALUES('San Diego',817541, 'IA');
INSERT INTO City(CityName, Population, StateCode) VALUES('San Diego',6839401, 'SD');
INSERT INTO City(CityName, Population, StateCode) VALUES('San Francisco',7820706, 'MD');
INSERT INTO City(CityName, Population, StateCode) VALUES('San Francisco',2791355, 'MS');
INSERT INTO City(CityName, Population, StateCode) VALUES('San Francisco',8303440, 'NE');
INSERT INTO City(CityName, Population, StateCode) VALUES('San Jose',11877303, 'AL');
INSERT INTO City(CityName, Population, StateCode) VALUES('San Jose',7025397, 'IA');
INSERT INTO City(CityName, Population, StateCode) VALUES('San Jose',8713838, 'ME');
INSERT INTO City(CityName, Population, StateCode) VALUES('Santa Ana',7542170, 'LA');
INSERT INTO City(CityName, Population, StateCode) VALUES('Santa Ana',11641031, 'UT');
INSERT INTO City(CityName, Population, StateCode) VALUES('Seattle',6342350, 'HI');
INSERT INTO City(CityName, Population, StateCode) VALUES('Seattle',8919255, 'ND');
INSERT INTO City(CityName, Population, StateCode) VALUES('Seattle',4576392, 'NM');
INSERT INTO City(CityName, Population, StateCode) VALUES('Shreveport',6768568, 'TX');
INSERT INTO City(CityName, Population, StateCode) VALUES('Shreveport',7695528, 'VT');
INSERT INTO City(CityName, Population, StateCode) VALUES('Shreveport',2420369, 'WY');
INSERT INTO City(CityName, Population, StateCode) VALUES('Spokane',636286, 'NJ');
INSERT INTO City(CityName, Population, StateCode) VALUES('Spokane',4281152, 'TN');
INSERT INTO City(CityName, Population, StateCode) VALUES('St. Louis',7594582, 'NC');
INSERT INTO City(CityName, Population, StateCode) VALUES('St. Louis',595768, 'RI');
INSERT INTO City(CityName, Population, StateCode) VALUES('St. Louis',145689, 'WY');
INSERT INTO City(CityName, Population, StateCode) VALUES('St. Paul',5161245, 'CT');
INSERT INTO City(CityName, Population, StateCode) VALUES('St. Paul',4562887, 'GA');
INSERT INTO City(CityName, Population, StateCode) VALUES('St. Paul',11310912, 'WI');
INSERT INTO City(CityName, Population, StateCode) VALUES('St. Petersburg',4843309, 'CT');
INSERT INTO City(CityName, Population, StateCode) VALUES('St. Petersburg',5367444, 'OK');
INSERT INTO City(CityName, Population, StateCode) VALUES('Stockton',11526559, 'ND');
INSERT INTO City(CityName, Population, StateCode) VALUES('Stockton',8214688, 'NM');
INSERT INTO City(CityName, Population, StateCode) VALUES('Tacoma',4181984, 'ID');
INSERT INTO City(CityName, Population, StateCode) VALUES('Tacoma',10845187, 'IL');
INSERT INTO City(CityName, Population, StateCode) VALUES('Tacoma',6965826, 'OK');
INSERT INTO City(CityName, Population, StateCode) VALUES('Tampa',9296125, 'MS');
INSERT INTO City(CityName, Population, StateCode) VALUES('Tampa',8901528, 'NE');
INSERT INTO City(CityName, Population, StateCode) VALUES('Toledo',6662145, 'KY');
INSERT INTO City(CityName, Population, StateCode) VALUES('Toledo',7049801, 'SC');
INSERT INTO City(CityName, Population, StateCode) VALUES('Toledo',8377152, 'SD');
INSERT INTO City(CityName, Population, StateCode) VALUES('Tucson',8142328, 'MI');
INSERT INTO City(CityName, Population, StateCode) VALUES('Tucson',2745552, 'NJ');
INSERT INTO City(CityName, Population, StateCode) VALUES('Tucson',11958750, 'TN');
INSERT INTO City(CityName, Population, StateCode) VALUES('Tulsa',8783024, 'HI');
INSERT INTO City(CityName, Population, StateCode) VALUES('Tulsa',8908456, 'NM');
INSERT INTO City(CityName, Population, StateCode) VALUES('Virginia Beach',5821114, 'CO');
INSERT INTO City(CityName, Population, StateCode) VALUES('Virginia Beach',5134235, 'MA');
INSERT INTO City(CityName, Population, StateCode) VALUES('Washington',7089351, 'AL');
INSERT INTO City(CityName, Population, StateCode) VALUES('Washington',1384044, 'ME');
INSERT INTO City(CityName, Population, StateCode) VALUES('Wichita',6134430, 'AK');
INSERT INTO City(CityName, Population, StateCode) VALUES('Wichita',11803323, 'PA');
INSERT INTO City(CityName, Population, StateCode) VALUES('Yonkers',10868202, 'LA');
INSERT INTO City(CityName, Population, StateCode) VALUES('Yonkers',8672133, 'MA');
INSERT INTO City(CityName, Population, StateCode) VALUES('Yonkers',116283, 'UT');

