INSERT INTO Campaign(Description) VALUES ('Art with an attitude.');
INSERT INTO Campaign(Description) VALUES ('Best art with the best attitude.');
INSERT INTO Campaign(Description) VALUES ('Best quality in low prices is our mission.');
INSERT INTO Campaign(Description) VALUES ('Comfort starts and ends at our furniture.');
INSERT INTO Campaign(Description) VALUES ('Crafted by highly specialized workers.');
INSERT INTO Campaign(Description) VALUES ('Crazy Cheap Prices!');
INSERT INTO Campaign(Description) VALUES ('Designed for your comfort.');
INSERT INTO Campaign(Description) VALUES ('Designing your home to the best.');
INSERT INTO Campaign(Description) VALUES ('Designs inspired by the new generation with a classic touch.');
INSERT INTO Campaign(Description) VALUES ('Dream furniture.');
INSERT INTO Campaign(Description) VALUES ('Fill your office with beautiful furniture.');
INSERT INTO Campaign(Description) VALUES ('Furnishing Your Home for Less.');
INSERT INTO Campaign(Description) VALUES ('Get More For Less.');
INSERT INTO Campaign(Description) VALUES ('Great Furniture. Better Prices.');
INSERT INTO Campaign(Description) VALUES ('Huge Furniture Sale Today!');
INSERT INTO Campaign(Description) VALUES ('Let your style make an impression on people.');
INSERT INTO Campaign(Description) VALUES ('Life is too short for boring furniture.');
INSERT INTO Campaign(Description) VALUES ('Look for comfort.');
INSERT INTO Campaign(Description) VALUES ('No one can design furniture like us.');
INSERT INTO Campaign(Description) VALUES ('Our furniture is the best.');
INSERT INTO Campaign(Description) VALUES ('Our name is the promise of standard and quality.');
INSERT INTO Campaign(Description) VALUES ('Say goodbye to discomfort.');
INSERT INTO Campaign(Description) VALUES ('Shop the luxury furniture you need.');
INSERT INTO Campaign(Description) VALUES ('Sit with the luxury you have.');
INSERT INTO Campaign(Description) VALUES ('The art reflects the quality.');
INSERT INTO Campaign(Description) VALUES ('The Best Deal You Will Find!');
INSERT INTO Campaign(Description) VALUES ('The best design on the internet will be in your office.');
INSERT INTO Campaign(Description) VALUES ('The best furniture you can find on the planet.');
INSERT INTO Campaign(Description) VALUES ('The decoration is in the budget now.');
INSERT INTO Campaign(Description) VALUES ('The expression of beauty and love.');
INSERT INTO Campaign(Description) VALUES ('The expression of happiness.');
INSERT INTO Campaign(Description) VALUES ('The most awful design you will ever find.');
INSERT INTO Campaign(Description) VALUES ('The only furniture your office deserves.');
INSERT INTO Campaign(Description) VALUES ('Turn your dream into reality.');
INSERT INTO Campaign(Description) VALUES ('Where designs meet creativity.');
INSERT INTO Campaign(Description) VALUES ('You cant find such prices anywhere else.');
INSERT INTO Campaign(Description) VALUES ('You will sleep in comfort now.');
INSERT INTO Campaign(Description) VALUES ('Your imagination, our creation.');
INSERT INTO Campaign(Description) VALUES ('Your perfect hall for furniture needs.');

